[project]
name = "aurora-postgresql-log-archive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools>=3.4.0",
    "boto3>=1.35.92",
    "boto3-stubs[rds,s3,sts]==1.35.92",
]
